packages:
  - 'packages/*'
  - 'examples/*'
  - 'website'
allowBuilds:
  '@swc/core': false
  esbuild: false
  sharp: false
  unrs-resolver: false
linkWorkspacePackages: deep
strictPeerDependencies: true
