packages:
  - 'packages/*'
  - 'examples/*'
  - 'website'
linkWorkspacePackages: deep
strictPeerDependencies: true
ignoreWorkspaceRootCheck: true
allowBuilds:
  esbuild: false
  sharp: false
minimumReleaseAgeExclude:
  - starlight-theme-nova@0.12.1
